import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, ArrowRight, Sprout, Fingerprint, Eye, Leaf, LockKeyhole } from 'lucide-react';
import { getContractAddress, getNetwork } from '../config';

export default function LandingPage() {
  const configured = Boolean(getContractAddress());
  return <div className="landing">
    <section className="hero" aria-labelledby="hero-title">
      <img className="hero-image" src="/images/stillroom-leaves.jpg" alt="Layers of deep green leaves, a quiet glimpse into the garden" width="2000" height="3556" fetchPriority="high" />
      <div className="hero-shade" />
      <div className="hero-topline"><span><span className="small-star">✳</span> A private space. An open invitation.</span><span className="hero-edition">Rooted in privacy</span></div>
      <div className="hero-copy"><h1 id="hero-title">Room to belong.<br />Space to be<br />yourself.</h1><p>A thoughtful threshold for your community.<br className="desktop-break" /> Prove the rule, without publishing your score.</p><div className="hero-actions"><Link className="btn btn-saffron" to="/gate">Enter the gate <ArrowUpRight size={18} aria-hidden="true" /></Link><Link className="hero-text-link" to="/privacy">Discover our philosophy <ArrowRight size={16} aria-hidden="true" /></Link></div></div>
      <div className="society-seal" aria-hidden="true"><span>The Stillroom society</span><Sprout size={48} strokeWidth={1} /><span>Grow on your own terms</span></div>
      <div className="hero-bottom"><span>Less revealed. More room to grow.</span><a href="#how-it-works" aria-label="Explore how Stillroom works"><ArrowDown size={17} aria-hidden="true" /> Take a closer look</a></div>
    </section>
    <div className="garden-status"><div className="garden-status-title"><span className="outlined-leaf"><Leaf size={19} aria-hidden="true" /></span><div><strong>Your place in the garden starts here.</strong><span>A private-access protocol on Midnight.</span></div></div><div className="garden-status-live"><span className="network-dot" /><span>{getNetwork() === 'preview' ? 'Preview' : 'Preprod'} network</span><span className="status-divider" /><span>{configured ? 'Contract configured' : 'Awaiting a planted gate'}</span></div><Link to={configured ? '/observatory' : '/admin'} className="text-link">{configured ? 'Visit the observatory' : 'Configure a gate'}<ArrowUpRight size={16} aria-hidden="true" /></Link></div>
    <section className="introduction section" id="how-it-works" aria-labelledby="intro-title"><div className="intro-heading"><span className="section-label"><Sprout size={16} aria-hidden="true" /> A different way in</span><h2 id="intro-title">Belonging shouldn’t<br />cost your privacy.</h2><p>Some spaces are worth keeping a little quieter. Stillroom lets communities welcome people through a shared rule, rather than a collection of personal details.</p><Link className="text-link" to="/privacy">Read our privacy principles <ArrowUpRight size={17} aria-hidden="true" /></Link></div><ol className="process-list"><li><span className="step-number">01</span><div><h3>A shared threshold</h3><p>A steward sets the entry rule, capacity and opening period. Everyone can see the same terms.</p></div><Sprout size={22} strokeWidth={1.4} aria-hidden="true" /></li><li><span className="step-number">02</span><div><h3>Your proof, not your particulars</h3><p>Your wallet helps prove that your private input meets the rule. The score isn’t published to the ledger.</p></div><Fingerprint size={22} strokeWidth={1.4} aria-hidden="true" /></li><li><span className="step-number">03</span><div><h3>An entry, without a dossier</h3><p>The public record keeps a count and a one-use proof marker, not your private passphrase.</p></div><Eye size={22} strokeWidth={1.4} aria-hidden="true" /></li></ol></section>
    <section className="principle-section" aria-labelledby="principle-title"><figure className="botanical-photo"><img src="/images/stillroom-growing.jpg" alt="A green garden trowel resting beside potting soil and a small planter" width="1000" height="667" loading="lazy" /><figcaption>Good things need room to grow.</figcaption></figure><div className="principle-copy"><span className="section-label"><LockKeyhole size={15} aria-hidden="true" /> Private by intention</span><h2 id="principle-title">A little less exposure.<br />A little more trust.</h2><p>A garden has a gate, not a glass wall. We believe access can work the same way: clear boundaries, verifiable rules, and respect for what stays yours.</p><div className="principle-note"><Leaf size={20} aria-hidden="true" /><p><strong>An honest note on this experiment</strong>The current score is self-attested, not an independently verified credential. Stillroom demonstrates private rule-checking; it does not verify real-world membership.</p></div><Link className="text-link" to="/observatory">See what is public <ArrowUpRight size={17} aria-hidden="true" /></Link></div></section>
    <section className="closing-invitation"><div><span className="section-label">There is room for you here</span><h2>Step inside. Stay yourself.</h2></div><Link className="btn btn-primary" to="/gate">Explore the gate <ArrowUpRight size={18} aria-hidden="true" /></Link></section>
  </div>;
}
