import { ArrowUpRight, Eye, Fingerprint, Leaf } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function PhilosophyPage() {
  return <div className="page"><div className="page-heading"><span className="section-label"><Leaf size={16} /> Privacy & principles</span><h1>A gate, not a glass wall.</h1><p>Clear rules can coexist with personal boundaries. Stillroom uses Midnight to prove a relation over private inputs, while making the terms and outcome inspectable.</p></div>
    <div className="privacy-grid"><section className="privacy-box"><span className="section-label"><Eye size={17} /> The public side</span><h2>What the garden reveals</h2><ul><li>The threshold, capacity and deadline.</li><li>The pass and curator identifiers.</li><li>The steward’s public-key hash and open/closed flag.</li><li>Lifetime entry count, used pass IDs and nullifier receipts.</li><li>Contract address, circuit actions and transaction timing.</li></ul></section><section className="privacy-box"><span className="section-label"><Fingerprint size={17} /> The private side</span><h2>What stays off the ledger</h2><ul><li>The exact self-attested eligibility score.</li><li>The secret used to derive your proof marker.</li><li>The steward’s recovery secret.</li><li>The witness preimages used inside the circuit.</li></ul><p className="label" style={{ marginTop: 20 }}>“Off the ledger” is not “invisible to every service.” See the trust boundaries below.</p></section></div>
    <section className="reading-note"><h2>A proof is only as specific as its claim.</h2><p>A successful entry proves that a supplied score is between the public threshold and 100, while the gate is open, unexpired and below capacity. It also proves that the secret/pass combination has not been recorded before.</p><p>It does not prove someone’s identity, age, accredited status or real-world membership. The score is self-attested. A production service would need issuer-backed credentials, revocation and a separate policy for unique participation.</p></section>
    <section className="reading-note"><h2>The boundaries we do not hide.</h2><ul><li><strong>Proving infrastructure matters.</strong> Your wallet’s proof-generation path may process private inputs outside this tab. Use a trusted or local service for sensitive data.</li><li><strong>One receipt is not one person.</strong> Choosing another secret generates another marker. The same secret and pass ID also generate the same marker across deployments.</li><li><strong>Metadata remains.</strong> Transaction timing, wallet infrastructure and network requests may correlate activity. Stillroom does not promise total anonymity.</li><li><strong>Your browser is part of the trust boundary.</strong> Witnesses are held in session memory, not deliberately saved to localStorage. A compromised browser, extension or recovery backup can still expose them.</li><li><strong>Public rules reveal something.</strong> A successful proof implies that the threshold was met. Zero knowledge does not conceal the result you chose to prove.</li></ul></section>
    <div className="closing-invitation" style={{ margin: 0 }}><div><span className="section-label">Know the terms before you enter</span><h2>Privacy, with the footnotes.</h2></div><Link className="btn btn-primary" to="/gate">Visit the gate <ArrowUpRight size={17} /></Link></div>
  </div>;
}
